---
- name: Install nginx vhost
  hosts: webservers
  remote_user: runner
  become: true
  become_method: sudo
  gather_facts: false

  vars: 
    sites:
    - "fizmat.ru"
    - "etis.ru"
    - "kirill.com"
  
  roles:
  - nginx-vhosts